### ISSUE TITLE
Messed up repository ?

### ISSUE THREAD

**Issue by matlo607** [dougbradbury/cslim#34]
Hello @dougbradbury,

It seems you reverted more than we really wanted at the beginning.
Please compare with what I have on my [repository](https://github.com/matlo607/cslim/commits/master).

The following commits are missing :
- [VS2017] fix error C2016: C requires that a struct or union has at least one member
- [VS2013] error C3861: snprintf identifier not found
- ...
- use Serialies Release functino for free memory
- Merge branch 'fix-build-visual-studio-2017' of github.com:matlo607/cs…
- move snprintf fixes to a compatibility file

I may have missed some of them.
What exactly happened there ?

**Comment by dougbradbury** [comment]
I went too far back when I reset... fixed it by pulling from yours!  I also pulled your cmake branch over onto my repository as well.  Where are you with the build?  Is it working?
